[tool.poetry]
name = "pystepikconnect"
version = "0.1.0"
description = ""
authors = ["Ilya Kuznetsov <ilkztsff@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
wheel = "^0.43.0"
sdist = "^0.0.0"
setuptools = "^70.3.0"
types-requests = "^2.32.0.20240622"
pydantic = "^2.8.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.0"
mypy = "^1.10.1"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
